# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'app_sw.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QMainWindow,
    QPushButton, QSizePolicy, QSpacerItem, QStackedWidget,
    QVBoxLayout, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(785, 559)
        MainWindow.setStyleSheet(u"/* -----------------------------------------\n"
"   GENERAL - Modern Glassmorphism UI\n"
"----------------------------------------- */\n"
"QWidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                stop:0 rgba(150, 50, 100, 0.9),   /* Dark pink on the left */\n"
"                                stop:1 rgba(80, 40, 140, 0.9));  /* Purple on the right */\n"
"    font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Roboto\", \"Helvetica\", sans-serif;\n"
"    font-size: 14px;\n"
"    color: #E8E0F5;                 /* Light purple text */\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   BUTTONS (GENERAL)\n"
"----------------------------------------- */\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 0.12);  /* Glass-like translucent */\n"
"    color: #F5F0FF;\n"
"    border: 1px solid rgba(255, 255, 255, 0.25);\n"
"    border-radius: 6px;\n"
"    padding: 0px;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    min-"
                        "height: 36px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.2);\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    /*box-shadow: 0 8px 24px rgba(180, 120, 220, 0.6);*/\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.15);\n"
"    transform: scale(0.98);\n"
"   /* box-shadow: 0 4px 12px rgba(200, 150, 220, 0.3);*/\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QPushButton:disabled {\n"
"    background-color: rgba(180, 170, 190, 0.3);\n"
"    color: rgba(45, 36, 64, 0.4);\n"
"    border: 1px solid rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton::icon {\n"
"    alignment: center;\n"
"}\n"
"\n"
"/* Secondary button style */\n"
"QPushButton[secondary=\"true\"] {\n"
"    background-color: rgba(255, 255, 255, 0.08);\n"
"    color: #F5F0FF;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2);\n"
"}\n"
"\n"
"QPushButton[secondary=\"true\"]:hover {\n"
"    background-color: rgba(255, 255, 255, 0.15);\n"
"    border: 1px solid rgba(255, 255, 2"
                        "55, 0.35);\n"
"    /*box-shadow: 0 8px 24px rgba(255, 255, 255, 0.2);*/\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   SIDEBAR\n"
"----------------------------------------- */\n"
"QFrame#sidebar {\n"
"    background-color: rgba(255, 255, 255, 0.08);  /* Very translucent to see background through */\n"
"    border-right: 1px solid rgba(200, 160, 220, 0.3);\n"
"    border-radius: 0px;\n"
"    padding: 20px 1px;\n"
"}\n"
"\n"
"/* Logo styling */\n"
"QLabel#logo_gif {\n"
"    background-color: transparent;\n"
"    border-radius: 12px;\n"
"    padding: 16px 0px;\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   SIDEBAR BUTTONS (Glowing Effect)\n"
"----------------------------------------- */\n"
"QPushButton#filter_pg_btn,\n"
"QPushButton#gallery_pg_btn,\n"
"QPushButton#profile_pg_btn {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #2D2440;\n"
"    padding: 14px 16px;\n"
"    border-radius: 14px;\n"
"    text-align: left;\n"
"    font-weight: 500;\n"
""
                        "    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton#filter_pg_btn:hover,\n"
"QPushButton#gallery_pg_btn:hover,\n"
"QPushButton#profile_pg_btn:hover {\n"
"    background-color: rgba(220, 180, 240, 0.3);\n"
"    /*box-shadow: 0 0 20px rgba(200, 150, 230, 0.6),\n"
"                0 0 40px rgba(200, 150, 230, 0.4),\n"
"                inset 0 0 20px rgba(255, 255, 255, 0.2);*/\n"
"    border: 1px solid rgba(230, 190, 250, 0.5);\n"
"}\n"
"\n"
"QPushButton#filter_pg_btn,\n"
"QPushButton#gallery_pg_btn,\n"
"QPushButton#profile_pg_btn {\n"
"    padding: 0px;                  /* Remove padding offsets */\n"
"    text-align: center;            /* Center icon */\n"
"    qproperty-iconSize: 28px 28px; /* (Optional) define icon size */\n"
"}\n"
"\n"
"/* Active/selected state */\n"
"QPushButton#filter_pg_btn[active=\"true\"],\n"
"QPushButton#gallery_pg_btn[active=\"true\"],\n"
"QPushButton#profile_pg_btn[active=\"true\"] {\n"
"    font-weight: 700;\n"
"    background-color: rgba(220, 180, 240, 0.4);\n"
"    /*box-shadow: 0 0 1"
                        "5px rgba(200, 150, 230, 0.5);*/\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   COMBO BOX\n"
"----------------------------------------- */\n"
"QComboBox {\n"
"    background-color: rgba(255, 255, 255, 0.5);\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    border-radius: 12px;\n"
"    padding: 10px 36px 10px 14px;\n"
"    color: #2D2440;\n"
"    font-weight: 500;\n"
"    font-size: 14px;\n"
"    min-height: 36px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid rgba(220, 180, 230, 0.6);\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    /*box-shadow: 0 4px 16px rgba(220, 180, 230, 0.3);*/\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid rgba(220, 180, 230, 0.8);\n"
"    /*box-shadow: 0 0 20px rgba(220, 180, 230, 0.4);*/\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 32px;\n"
"    border-left: none;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: "
                        "12px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/arrow_down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgba(250, 245, 255, 0.95);\n"
"    border: 1px solid rgba(220, 180, 230, 0.5);\n"
"    border-radius: 12px;\n"
"    selection-background-color: rgba(220, 180, 240, 0.4);\n"
"    selection-color: #2D2440;\n"
"    outline: 0;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    min-height: 38px;\n"
"    padding: 10px 14px;\n"
"    color: #2D2440;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(220, 180, 240, 0.3);\n"
"    /*box-shadow: 0 0 12px rgba(220, 180, 230, 0.4);*/\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   INPUT FIELDS (Glassmorphism)\n"
"----------------------------------------- */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: rgba(255, 255, 255, 0.5);\n"
"    border: 1px solid r"
                        "gba(255, 255, 255, 0.4);\n"
"    border-radius: 12px;\n"
"    padding: 11px 14px;\n"
"    color: #2D2440;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(220, 180, 230, 0.8);\n"
"    /*box-shadow: 0 0 20px rgba(220, 180, 230, 0.4);*/\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder, QTextEdit::placeholder {\n"
"    color: rgba(45, 36, 64, 0.5);\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   SCROLLBARS (Glassmorphism)\n"
"----------------------------------------- */\n"
"QScrollBar:vertical {\n"
"    background: rgba(255, 255, 255, 0.2);\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(220, 180, 230, 0.5);\n"
"    border-radius: 5px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(220, 180, 230, 0.8);\n"
"    /*box-shadow: 0 0 10p"
                        "x rgba(200, 150, 230, 0.6);*/\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, \n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: rgba(255, 255, 255, 0.2);\n"
"    height: 10px;\n"
"    border-radius: 5px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(220, 180, 230, 0.5);\n"
"    border-radius: 5px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(220, 180, 230, 0.8);\n"
"    box-shadow: 0 0 10px rgba(200, 150, 230, 0.6);\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   TABLE VIEWS\n"
"----------------------------------------- */\n"
"QTableView {\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    gridline-color: rgba(220, 180, 230, 0.2);\n"
"    color: #2D2440;\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    border-radius: 12px;\n"
"    selection-background-color: rgba(220, 180, 240, 0"
                        ".3);\n"
"    selection-color: #2D2440;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgba(240, 235, 250, 0.6);\n"
"    color: #2D2440;\n"
"    border: none;\n"
"    border-bottom: 1px solid rgba(220, 180, 230, 0.3);\n"
"    padding: 12px 10px;\n"
"    font-weight: 600;\n"
"    font-size: 12px;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.8px;\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   CARDS / FRAMES\n"
"----------------------------------------- */\n"
"QFrame[card=\"true\"] {\n"
"    background-color: rgba(255, 255, 255, 0.5);\n"
"    border: 1px solid rgba(255, 255, 255, 0.4);\n"
"    border-radius: 16px;\n"
"    /*box-shadow: 0 8px 32px rgba(200, 150, 230, 0.2);*/\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   SIDEBAR (Rounded Glass Panel)\n"
"----------------------------------------- */\n"
"QFrame#sidebar {\n"
"    background-color: rgba(255, 255, 255, 0.08);\n"
"    border-right: 1px solid rgba(200, 160, 220, 0.3);\n"
"\n"
"    bo"
                        "rder-radius: 10px;     /* Round the corners */\n"
"    margin: 6px;            /* Push away from window so radius is visible */\n"
"    padding: 20px 1px;\n"
"}\n"
"\n"
"\n"
"/* -----------------------------------------\n"
"   LABELS (Headers)\n"
"----------------------------------------- */\n"
"QLabel[heading=\"true\"] {\n"
"    font-weight: 700;\n"
"    font-size: 18px;\n"
"    color: #2D2440;\n"
"}\n"
"\n"
"QLabel[subheading=\"true\"] {\n"
"    font-weight: 500;\n"
"    font-size: 14px;\n"
"    color: rgba(45, 36, 64, 0.7);\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   SEPARATORS\n"
"----------------------------------------- */\n"
"QFrame[separator=\"true\"] {\n"
"    background-color: rgba(220, 180, 230, 0.3);\n"
"    max-height: 1px;\n"
"    min-height: 1px;\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   TABS (Glassmorphism)\n"
"----------------------------------------- */\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"    background-color: rgba(255, 255, 255, 0."
                        "4);\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: transparent;\n"
"    color: rgba(45, 36, 64, 0.6);\n"
"    border: none;\n"
"    border-bottom: 2px solid transparent;\n"
"    padding: 12px 20px;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    color: #2D2440;\n"
"    background-color: rgba(220, 180, 240, 0.2);\n"
"    /*box-shadow: 0 0 15px rgba(200, 150, 230, 0.4);*/\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: #2D2440;\n"
"    border-bottom: 2px solid rgba(200, 150, 230, 0.8);\n"
"    background-color: rgba(220, 180, 240, 0.3);\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   CHECKBOXES & RADIO BUTTONS\n"
"----------------------------------------- */\n"
"QCheckBox, QRadioButton {\n"
"    color: #2D2440;\n"
"    spacing: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator, QRadioButton::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(220, 180"
                        ", 230, 0.5);\n"
"    background-color: rgba(255, 255, 255, 0.5);\n"
"}\n"
"\n"
"QCheckBox::indicator:hover, QRadioButton::indicator:hover {\n"
"    border: 2px solid rgba(220, 180, 230, 0.8);\n"
"    /*box-shadow: 0 0 12px rgba(200, 150, 230, 0.5);*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgba(220, 180, 230, 0.8);\n"
"    border: 2px solid rgba(200, 150, 230, 0.9);\n"
"    image: url(:/icons/check_white.svg);\n"
"    /*box-shadow: 0 0 15px rgba(200, 150, 230, 0.6);*/\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: rgba(220, 180, 230, 0.8);\n"
"    border: 5px solid rgba(255, 255, 255, 0.9);\n"
"    /*box-shadow: 0 0 15px rgba(200, 150, 230, 0.6);*/\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   TOOLTIPS\n"
"----------------------------------------- */\n"
"QToolTip {\n"
"    background-color: rgba(240, 235, 250, 0.95);\n"
"    color: #2D2440;\n"
"    border: 1px s"
                        "olid rgba(220, 180, 230, 0.5);\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    font-size: 12px;\n"
"    /*box-shadow: 0 4px 16px rgba(200, 150, 230, 0.3);*/\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   MENU & CONTEXT MENUS\n"
"----------------------------------------- */\n"
"QMenu {\n"
"    background-color: rgba(250, 245, 255, 0.95);\n"
"    border: 1px solid rgba(220, 180, 230, 0.5);\n"
"    border-radius: 12px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 10px 16px;\n"
"    border-radius: 8px;\n"
"    color: #2D2440;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: rgba(220, 180, 240, 0.4);\n"
"    /*box-shadow: 0 0 12px rgba(200, 150, 230, 0.4);*/\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: rgba(220, 180, 230, 0.3);\n"
"    margin: 6px 10px;\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   DIALOGS & MESSAGE BOXES\n"
"----------------------------------------- */\n"
"QDialog {\n"
""
                        "    background-color: rgba(240, 230, 250, 0.95);\n"
"}\n"
"\n"
"QMessageBox {\n"
"    background-color: rgba(240, 230, 250, 0.95);\n"
"}\n"
"\n"
"/* -----------------------------------------\n"
"   PROGRESS BARS\n"
"----------------------------------------- */\n"
"QProgressBar {\n"
"    background-color: rgba(255, 255, 255, 0.4);\n"
"    border: 1px solid rgba(220, 180, 230, 0.3);\n"
"    border-radius: 6px;\n"
"    height: 8px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgba(220, 180, 230, 0.8);\n"
"    border-radius: 5px;\n"
"    /*box-shadow: 0 0 10px rgba(200, 150, 230, 0.5);*/\n"
"}\n"
"\n"
"/*side bar stuff here change it if needed*/\n"
"/* -----------------------------------------\n"
"   SCROLL AREA - Sidebar-style Glass\n"
"----------------------------------------- */\n"
"QScrollArea{\n"
"    background-color: rgba(255, 255, 255, 0.08);  /* Very translucent like sidebar */\n"
"    border: 1px solid rgba(200, 160, 220, 0.3);   /* Subtle glass border */\n"
""
                        "    border-radius: 10px;                           /* Rounded corners to match sidebar */\n"
"    padding: 10px;                                 /* Inner padding */\n"
"}\n"
"\n"
"QScrollArea{\n"
"    background-color: transparent;                /* Keep the inner container transparent */\n"
"    border-radius: 10px;                           /* Match outer radius */\n"
"}\n"
"\n"
"/* Optional: Scrollbars in sidebar style */\n"
"QScrollBar:vertical {\n"
"    background: rgba(255, 255, 255, 0.2);\n"
"    width: 10px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(220, 180, 230, 0.5);\n"
"    border-radius: 5px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(220, 180, 230, 0.8);\n"
"    /*box-shadow: 0 0 10px rgba(200, 150, 230, 0.6);*/\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    background: none;\n"
"}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.sidebar = QFrame(self.centralwidget)
        self.sidebar.setObjectName(u"sidebar")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar.sizePolicy().hasHeightForWidth())
        self.sidebar.setSizePolicy(sizePolicy)
        self.sidebar.setMinimumSize(QSize(62, 0))
        self.sidebar.setMaximumSize(QSize(62, 16777215))
        self.sidebar.setFrameShape(QFrame.Shape.StyledPanel)
        self.sidebar.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.sidebar)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer_2)

        self.filter_pg_btn = QPushButton(self.sidebar)
        self.filter_pg_btn.setObjectName(u"filter_pg_btn")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.filter_pg_btn.sizePolicy().hasHeightForWidth())
        self.filter_pg_btn.setSizePolicy(sizePolicy1)
        self.filter_pg_btn.setMinimumSize(QSize(0, 36))
        self.filter_pg_btn.setMaximumSize(QSize(40, 40))
        icon = QIcon()
        icon.addFile(u":/icons/assets/paintbrush-pencil.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.filter_pg_btn.setIcon(icon)
        self.filter_pg_btn.setIconSize(QSize(28, 28))

        self.verticalLayout_2.addWidget(self.filter_pg_btn)

        self.gallery_pg_btn = QPushButton(self.sidebar)
        self.gallery_pg_btn.setObjectName(u"gallery_pg_btn")
        sizePolicy1.setHeightForWidth(self.gallery_pg_btn.sizePolicy().hasHeightForWidth())
        self.gallery_pg_btn.setSizePolicy(sizePolicy1)
        self.gallery_pg_btn.setMaximumSize(QSize(40, 40))
        icon1 = QIcon()
        icon1.addFile(u":/icons/assets/picture.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.gallery_pg_btn.setIcon(icon1)
        self.gallery_pg_btn.setIconSize(QSize(28, 28))

        self.verticalLayout_2.addWidget(self.gallery_pg_btn)

        self.profile_pg_btn = QPushButton(self.sidebar)
        self.profile_pg_btn.setObjectName(u"profile_pg_btn")
        self.profile_pg_btn.setMaximumSize(QSize(40, 40))
        icon2 = QIcon()
        icon2.addFile(u":/icons/assets/user.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.profile_pg_btn.setIcon(icon2)
        self.profile_pg_btn.setIconSize(QSize(28, 28))

        self.verticalLayout_2.addWidget(self.profile_pg_btn)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)


        self.horizontalLayout.addWidget(self.sidebar)

        self.windows = QStackedWidget(self.centralwidget)
        self.windows.setObjectName(u"windows")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.windows.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.windows.addWidget(self.page_2)

        self.horizontalLayout.addWidget(self.windows)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.filter_pg_btn.setText("")
        self.gallery_pg_btn.setText("")
        self.profile_pg_btn.setText("")
    # retranslateUi

